wasamasa/gotham-theme

gotham-theme.el
Add support for linum-relative  package.
Screenshot:
=> Add linum-relative support

gotham-theme.el
Hi and thank you for this wonderful theme. Some simple additions which I hope can be merged.
=> Add anzu and volatile-highlight support

gotham-theme.el
=> Add SLIME support

gotham-theme.el
Should look good, I copied the colors from Ivy. #25 related.
=> Add ace-window and avy support

gotham-theme.el
#25 related, should look good.
=> Add lispy support

gotham-theme.el
#25 related, a bit obscure feature.
=> Add Ruler support

gotham-theme.el
#25 related, final pull request for now.
=> Add NeoTree support

gotham-theme.el
=> Add dired-async support

gotham-theme.el
Felt a bit too dark for unread messages.
=> Brighter color for Gnus unread articles

gotham-theme.el
Swapped orange with yellow because the preview was a bit difficult to see.
=> Company preview tweak

gotham-theme.el
Debbugs support and moving dired-async to external packages.
=> Add debbugs, move dired-async

gotham-theme.el
Face added in latest update to `dired-async`.
=> Add dired-async-failures face

gotham-theme.el
Faces for the Elfeed log buffer.
=> Add elfeed-log faces

gotham-theme.el
This adds support for the built-in `re-builder` package.
=> re-builder support

gotham-theme.el
Support for [info+](https://www.emacswiki.org/emacs/InfoPlus).
=> Add info+ support

gotham-theme.el
Move `elfeed` to external packages, add missing `ivy-cursor` face.
=> Move elfeed, add ivy-cursor

gotham-theme.el
support for cfw-calendar added
=> added cfw-calender

gotham-theme.el
Support for the [wgrep](https://github.com/mhayashi1120/Emacs-wgrep) package.
=> Add wgrep support

gotham-theme.el
=> Update Elfeed faces

gotham-theme.el
=> Add native line number support
